"""provider_id constraint changed..

Revision ID: 369e11473734
Revises: 2adbe0367aff
Create Date: 2025-04-01 21:50:28.869006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369e11473734'
down_revision: Union[str, None] = '2adbe0367aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_provider_id_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_provider_id_key', 'user', ['provider_id'])
    # ### end Alembic commands ###
