"""Datatpe of column has been changed to text

Revision ID: dbfbabe95eab
Revises: ae79dee978de
Create Date: 2025-04-01 15:39:49.615093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfbabe95eab'
down_revision: Union[str, None] = 'ae79dee978de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('user', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('user', 'provider_id',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'provider_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('user', 'provider',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
